# Start AeroSpace at login
start-at-login = true

[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-ctrl-c = 'layout tiles horizontal accordion'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-ctrl-s = 'focus --boundaries-action wrap-around-the-workspace right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-ctrl-shift-h = 'move left'
alt-ctrl-shift-s = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-ctrl-t = 'resize smart -100'
alt-ctrl-n = 'resize smart +100'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-ctrl-m = 'workspace 0'
alt-ctrl-w = 'workspace 1'
alt-ctrl-v = 'workspace 2'
alt-ctrl-z = 'workspace 3'
alt-ctrl-4 = 'workspace 4'
alt-ctrl-5 = 'workspace 5'
alt-ctrl-6 = 'workspace 6'
alt-ctrl-7 = 'workspace 7'
alt-ctrl-8 = 'workspace 8'
alt-ctrl-9 = 'workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-ctrl-shift-m = 'move-node-to-workspace 0'
alt-ctrl-shift-w = 'move-node-to-workspace 1'
alt-ctrl-shift-v = 'move-node-to-workspace 2'
alt-ctrl-shift-z = 'move-node-to-workspace 3'
alt-ctrl-shift-4 = 'move-node-to-workspace 4'
alt-ctrl-shift-5 = 'move-node-to-workspace 5'
alt-ctrl-shift-6 = 'move-node-to-workspace 6'
alt-ctrl-shift-7 = 'move-node-to-workspace 7'
alt-ctrl-shift-8 = 'move-node-to-workspace 8'
alt-ctrl-shift-9 = 'move-node-to-workspace 9'

# Reload config
alt-ctrl-shift-r = 'reload-config'

# Toggle fullscreen
alt-ctrl-f = 'fullscreen'

# Toggle float
alt-ctrl-g = 'layout floating tiling'
